// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1yXiOvEXjNJ-EsKp5oOh5jJ6tcjpaRLA',
    appId: '1:1076409384850:web:8c674b72f829027c8ccb4b',
    messagingSenderId: '1076409384850',
    projectId: 'tailsgram-dccf7',
    authDomain: 'tailsgram-dccf7.firebaseapp.com',
    storageBucket: 'tailsgram-dccf7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PMGYN78sece3dS7uIud3NLbTHEapFRw',
    appId: '1:1076409384850:android:e9b061af69da42848ccb4b',
    messagingSenderId: '1076409384850',
    projectId: 'tailsgram-dccf7',
    storageBucket: 'tailsgram-dccf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-ASa-EicRbaEHlKwUSygeuYXWj6iqv4',
    appId: '1:1076409384850:ios:1665410d3041abb58ccb4b',
    messagingSenderId: '1076409384850',
    projectId: 'tailsgram-dccf7',
    storageBucket: 'tailsgram-dccf7.firebasestorage.app',
    iosBundleId: 'com.example.tailsgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3-ASa-EicRbaEHlKwUSygeuYXWj6iqv4',
    appId: '1:1076409384850:ios:1665410d3041abb58ccb4b',
    messagingSenderId: '1076409384850',
    projectId: 'tailsgram-dccf7',
    storageBucket: 'tailsgram-dccf7.firebasestorage.app',
    iosBundleId: 'com.example.tailsgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1yXiOvEXjNJ-EsKp5oOh5jJ6tcjpaRLA',
    appId: '1:1076409384850:web:b28da0097e90ca118ccb4b',
    messagingSenderId: '1076409384850',
    projectId: 'tailsgram-dccf7',
    authDomain: 'tailsgram-dccf7.firebaseapp.com',
    storageBucket: 'tailsgram-dccf7.firebasestorage.app',
  );

}